<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function readMessage($messageId, $currentUserId){

        $message = $this->find($messageId);
        if( $message->getRead()==false && $message->getUserReceiver()->getId()==$currentUserId){

            $message->setRead(true);
            $this->getEntityManager()->flush();
        }
    }
    
    public function findMessages($emitterId, $receiverId, $read){
        
        $qb = $this->createQueryBuilder("m")->orderBy("m.createDatetime", "DESC");
        if( $emitterId!=null ){
            $qb->join("m.userEmitter", "ue");
            $qb->where('ue.id=:emitterId');
            $qb->setParameter('emitterId', $emitterId);
        }
        if( $receiverId!=null ){
            $qb->join("m.userReceiver", "ur");
            $qb->where('ur.id=:receiverId');
            $qb->setParameter('receiverId', $receiverId);
        }
        if( $read!=null ){
            $qb->where('read=:read')->setParameter('read', $read);
        }
        
        return $qb->getQuery()->getResult();
    }
}
