<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findOneByEmailAndPassword($email, $password){
        
        $query = $this->_em->createQuery(
                "  SELECT   u "
                . "FROM     MainBundle:User u WHERE u.email=:email "
                . "         AND u.password=:password");
        $query->setParameter('email', $email);
        $query->setParameter('password', $password);
        
        return $query->getSingleResult();
    }
}
